listen: "127.0.0.1:8765"

ros:
  enabled: true
  url: "ws://127.0.0.1:18766"

custom:
  - name: "custom_a"
    url: "ws://127.0.0.1:18767"
    topic_prefixes: ["/custom_a/"]
    package_prefixes: ["custom_a_description"]
    default: true

  # - name: "custom_b"
  #   url: "ws://127.0.0.1:18768"
  #   topic_prefixes: ["/custom_b/"]
  #   package_prefixes: ["custom_b_description"]

